update pipeline

diff --git a/.github/workflows/catalog-service-ci-cd.yml b/.github/workflows/catalog-service-ci-cd.yml
--- a/.github/workflows/catalog-service-ci-cd.yml
+++ b/.github/workflows/catalog-service-ci-cd.yml
@@ -79,7 +79,25 @@ jobs:
           username: ${{ secrets.DEPLOYMENT_MACHINE_USER }}
           password: ${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}
           script: |
-           echo "Starting Java service..."
-           nohup java -jar ~/service-catalog/service-catalog.jar --server.port=8082 > service-catalog.log 2>&1 &
-           echo "Service deployed successfully!"
+            mkdir -p ~/service-catalog
 
+            echo "Stopping any running instance of the Java service..."
+            pkill -f 'java.*service-catalog.jar' || echo "No existing service to stop."
+
+            sleep 5
+
+            echo "Starting Java service..."
+            nohup java -jar ~/service-catalog/service-catalog.jar --server.port=8082 > service-catalog.log 2>&1 &
+            echo "Service deployed successfully!"
+
+
+            echo "Waiting for service to initialize..."
+            sleep 10
+
+            echo "Checking application logs for errors..."
+            tail -n 20 ~/service-catalog/app.log
+
+            echo "Performing health check..."
+            curl -s http://localhost:8082/health || (echo "Service health check failed!" && exit 1)
+
+            echo "Service deployed successfully!"
