update pipeline

diff --git a/.github/workflows/catalog-service-ci-cd.yml b/.github/workflows/catalog-service-ci-cd.yml
--- a/.github/workflows/catalog-service-ci-cd.yml
+++ b/.github/workflows/catalog-service-ci-cd.yml
@@ -79,25 +79,18 @@ jobs:
           username: ${{ secrets.DEPLOYMENT_MACHINE_USER }}
           password: ${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}
           script: |
-            mkdir -p ~/service-catalog
 
             echo "Stopping any running instance of the Java service..."
             pkill -f 'java.*service-catalog.jar' || echo "No existing service to stop."
 
-            sleep 5
-
-            echo "Starting Java service..."
-            nohup java -jar ~/service-catalog/service-catalog.jar --server.port=8082 > service-catalog.log 2>&1 &
-            echo "Service deployed successfully!"
-
-
-            echo "Waiting for service to initialize..."
             sleep 10
 
-            echo "Checking application logs for errors..."
-            tail -n 20 ~/service-catalog/app.log
-
+            echo "Starting Java service..."
+            cd ~/service-catalog
+            nohup java -jar service-catalog.jar --server.port=8082 > service-catalog.log 2>&1 &
+            echo "Service deployed successfully!"
+            
             echo "Performing health check..."
-            curl -s http://localhost:8082/health || (echo "Service health check failed!" && exit 1)
+            curl -X 'GET'   'http://localhost:8082/products'   -H 'accept: /' || (echo "Service health check failed!" && exit 1)
 
             echo "Service deployed successfully!"
