Update inventory-ci-cd.yml

diff --git a/.github/workflows/inventory-ci-cd.yml b/.github/workflows/inventory-ci-cd.yml
--- a/.github/workflows/inventory-ci-cd.yml
+++ b/.github/workflows/inventory-ci-cd.yml
@@ -50,7 +50,7 @@ jobs:
 
       - name: Verify if the correct JAR file exists
         run: |
-          ls /home/runner/work/projet-soa-ecommerce-enit-2024-3AINFO2/projet-soa-ecommerce-enit-2024-3AINFO2/service-inventory.jar || (echo "JAR file not found!" && exit 1)
+          ls target/service-inventory.jar || (echo "JAR file not found!" && exit 1)
 
       - name: Add Server to Known Hosts
         run: |
