update pipeline

diff --git a/.github/workflows/order-ci-cd.yml b/.github/workflows/order-ci-cd.yml
--- a/.github/workflows/order-ci-cd.yml
+++ b/.github/workflows/order-ci-cd.yml
@@ -27,14 +27,11 @@ jobs:
           cd order/
           mvn clean package -DskipTests -Djava.version=17
 
-      - name: Debug Maven Build Output
-        run: ls -l order/target/
-
       - name: Archive JAR Artifact
         uses: actions/upload-artifact@v3
         with:
           name: order.jar
-          path: order/target/order*.jar
+          path: order/target/*.jar
 
   deploy:
     runs-on: ubuntu-latest
@@ -49,32 +46,33 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: order.jar
-          path: ./
+          path: ./ 
 
-      - name: Verify Downloaded JAR File
-        run: ls -l *.jar
+      - name: Verify if the correct JAR file exists
+        run: |
+          ls *.jar || (echo "JAR file not found!" && exit 1)
 
       - name: Add Server to Known Hosts
         run: |
           mkdir -p ~/.ssh
           ssh-keyscan -H ${{ secrets.DEPLOYMENT_MACHINE_IP }} >> ~/.ssh/known_hosts
 
-      - name: Create Destination Directory on VPS
+      - name: Create destination directory on VPS
         run: |
           sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" ssh ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
           "mkdir -p ~/order"
-
+      
       - name: Transfer JAR to VPS
         run: |
-          sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" scp order*.jar \
+          sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" scp order.jar \
           ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }}:~/order/order.jar
 
-      - name: Verify JAR File on VPS
+      - name: Verify if the JAR file exists on the VPS
         run: |
           sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" ssh ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
           "ls -l ~/order/order.jar"
 
-      - name: Show System Resources on VPS
+      - name: Show system resources usage after file transfer
         run: |
           sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" ssh ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }} \
           "df -h && free -h && top -bn1 | grep 'Cpu(s)'"
@@ -86,6 +84,8 @@ jobs:
           username: ${{ secrets.DEPLOYMENT_MACHINE_USER }}
           password: ${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}
           script: |
+            sleep 10
+
             echo "Starting Spring Boot service..."
             cd ~/order
             nohup java -jar order.jar --server.port=8083 > order.log 2>&1 &
@@ -97,4 +97,5 @@ jobs:
             curl -X 'GET' 'http://localhost:8083/actuator/health' -H 'accept: application/json' || (echo "Service health check failed!" && exit 1)
 
             echo "Service deployed and healthy!"
+            
             tail -n 50 ~/order/order.log
