update pipeline

diff --git a/.github/workflows/payment-ci-cd.yml b/.github/workflows/payment-ci-cd.yml
--- a/.github/workflows/payment-ci-cd.yml
+++ b/.github/workflows/payment-ci-cd.yml
@@ -1,9 +1,6 @@
-name: CI/CD Pipeline
+name: Payment CI/CD Pipeline
 
 on:
-  push:
-    branches:
-      - payment
   pull_request:
     branches:
       - payment
@@ -19,40 +16,28 @@ jobs:
       - name: Set up JDK 21
         uses: actions/setup-java@v2
         with:
-         distribution: 'adopt'
-         java-version: '21'
-
+          distribution: 'adopt'
+          java-version: '21'
 
       - name: Build with Maven
         run: |
           cd payment/
           mvn clean package -Dquarkus.package.type=uber-jar
 
-
-      - name: Archive JAR Artifact
-        uses: actions/upload-artifact@v3
+      - name: Archive test reports
+        if: failure()
+        uses: actions/upload-artifact@v2
         with:
-          name: payment.jar
-          path: payment/target/*-runner.jar
+          name: surefire-reports
+          path: payment/target/surefire-reports
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build
-    timeout-minutes: 30
-
-    steps:
-      - name: Install sshpass
-        run: sudo apt-get install -y sshpass
-
-      - name: Download JAR Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: payment.jar
-          path: ./
+      - name: Display test results
+        if: failure()
+        run: cat payment/target/surefire-reports/*.txt
 
       - name: Verify if the correct JAR file exists
         run: |
-          ls payment-1.0.0-SNAPSHOT-runner.jar || (echo "JAR file not found!" && exit 1)
+          ls payment/target/payment-1.0.0-SNAPSHOT-runner.jar || (echo "JAR file not found!" && exit 1)
 
       - name: Add Server to Known Hosts
         run: |
@@ -61,7 +46,7 @@ jobs:
 
       - name: Transfer JAR to VPS
         run: |
-          sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" scp ./payment-1.0.0-SNAPSHOT-runner.jar \
+          sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" scp payment/target/payment-1.0.0-SNAPSHOT-runner.jar \
           ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }}:~/payment/payment.jar
 
       - name: Verify if the JAR file exists on the VPS
@@ -89,10 +74,3 @@ jobs:
             echo "Service deployed successfully!"
             
             sleep 30
-
-            echo "Performing health check..."
-            
-
-            echo "Service deployed successfully!"
-            
-            tail -n 50 ~/payment/payment.log
