Update pricing-pipeline.yml

diff --git a/.github/workflows/pricing-pipeline.yml b/.github/workflows/pricing-pipeline.yml
--- a/.github/workflows/pricing-pipeline.yml
+++ b/.github/workflows/pricing-pipeline.yml
@@ -50,7 +50,7 @@ jobs:
 
       - name: Verify if the correct JAR file exists
         run: |
-          ls target/service-pricing-*.jar || (echo "JAR file not found!" && exit 1)
+          ls ./service-pricing-*.jar || (echo "JAR file not found!" && exit 1)
 
       - name: Add Server to Known Hosts
         run: |
